env:
  browser: true
  es2021: true
  node: true
  jasmine: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - '@typescript-eslint'
  - 'jasmine'

rules:
  no-debugger: "error"
  jasmine/no-focused-tests: "error"
