--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: id
  value_before_type_cast: c97f00ae-921e-405f-bec9-319d1e42dadd
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: default_database_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: name
  value_before_type_cast: Trucklino Demo
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: slug
  value_before_type_cast: trucklino-demo
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: description
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: public
  value_before_type_cast: false
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: preview
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: index_page_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2019-02-05 10:27:35.009362'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2019-02-05 10:27:35.009362'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
