--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: default_database_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: id
  value_before_type_cast: c97f00ae-921e-405f-bec9-319d1e42dadd
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: name
  value_before_type_cast: Trucklino
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: slug
  value_before_type_cast: trucklino
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: description
  value_before_type_cast: Eine Welt voller Waren und ein einsamer Truck der sie an
    den Bestimmungsort bringen muss. Und dein Programm muss sagen wie das geht!
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: preview
  value_before_type_cast: 5b1920b8-9663-4e21-acff-3d9515f92623
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: index_page_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2019-02-05 10:27:35.009362'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2019-02-09 07:42:40.774616'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
