stages:
  - build
  - test
  - deploy

.services_config: &services_config
  services:
    - postgres:15-bullseye

variables:
  POSTGRES_DB: $database
  POSTGRES_USER: $username
  POSTGRES_PASSWORD: $password
  POSTGRES_HOST_AUTH_METHOD: trust
  TPUT_BIN: "true"

#  _           _ _     _
# | |__  _   _(_) | __| |
# | '_ \| | | | | |/ _` |
# | |_) | |_| | | | (_| |
# |_.__/ \__,_|_|_|\__,_|
#

build_main_image:
  stage: build
  resource_group: build_image
  image:
    entrypoint: [""]
    name: gcr.io/kaniko-project/executor:debug
  only:
    refs:
      - master
      - chore/build_image_with_kaniko
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"username\":\"${CI_REGISTRY_USER}\",\"password\":\"${CI_REGISTRY_PASSWORD}\"}}}" > /kaniko/.docker/config.json
    - export BUILD_ARGS=$(cat .tool-versions | sed -e 's/\([^ ]*\) \(.*\)/\1_VERSION=\2/' | tr "[:lower:]" "[:upper:]" | xargs -n1 echo --build-arg )
  script:
    - |
      /kaniko/executor ${BUILD_ARGS} \
      --skip-unused-stages \
      --cache=true \
      --cache-repo ${CI_REGISTRY_IMAGE}/cache \
      --context ${CI_PROJECT_DIR} \
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile \
      --destination ${CI_REGISTRY_IMAGE}:latest \
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  image: registry.akra.de/mari/blattwerkzeug:latest
  script:
    - cd client
    - make install-deps
    - make client-compile
    - make cli-compile
    - echo "Compile complete."
  artifacts:
    paths:
      - client/dist/cli/
    expire_in: 1 hour

#  _            _
# | |_ ___  ___| |_
# | __/ _ \/ __| __|
# | ||  __/\__ \ |_
#  \__\___||___/\__|
#
test_rubocop:
  stage: test
  image: registry.akra.de/mari/blattwerkzeug:latest
  interruptible: true
  before_script:
    - cd server
    - gem update --system
    - make install-deps
  script:
#    - bundle exec rubocop
    - echo "rubocop job is still skipped due to too many offenses and will be enabled later"

test_rspec:
  <<: *services_config
  stage: test
  image: registry.akra.de/mari/blattwerkzeug:latest
  interruptible: true
  variables:
    STACKPROF: 1
    RAILS_ENV: test
    CI: "1"
  before_script:
    - cd server
    - gem update --system
    - cp config/database.yml.sample.gitlab_ci config/database.yml
    - make install-deps
    - make setup-database-schema

  script:
    - bundle exec rspec spec
    - echo "executed rspec"

  dependencies:
    - build

test_client:
  stage: test
  image: registry.akra.de/mari/blattwerkzeug:latest
  interruptible: true
  variables:
    STACKPROF: 1
    RAILS_ENV: test
    CI: "1"

  before_script:
    - cd client
    - make install-deps
  script:
    - make test

#      _            _
#   __| | ___ _ __ | | ___  _   _
#  / _` |/ _ \ '_ \| |/ _ \| | | |
# | (_| |  __/ |_) | | (_) | |_| |
#  \__,_|\___| .__/|_|\___/ \__, |
#            |_|            |___/

deploy:
  stage: deploy
  script:
    - echo "Deploying application will be added later"
