image: marcusriemer/sqlino:test

pipelines:
  default:
    - step:
        caches:
          - node-client
          - node-schema
          - bundler-global
        script:
          - make install-deps
          - make dist
          - make -C server test
          - TEST_SINGLE_RUN=true make -C client test

definitions:
  caches:
    bundler-global: /usr/lib/ruby/gems/
    node-client: client/node_modules
    node-schema: schema/json/node_modules
