image: marcusriemer/sqlino:test

pipelines:
  default:
    - step:
        caches:
          - client/node_modules
        script:
          - make install-deps
          - make dist
          - make -C server test
          - TEST_SINGLE_RUN=true make test
