image: marcusriemer/sqlino:test

# Builds usually don't take longer then 10 minutes
options:
  max-time: 20

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Client Build and Test
        caches:
          - node-client
          - node-schema
        artifacts:
          - client/dist/**
        script:
          - make -C client install-deps
          - make -C client client-compile
          - make -C client cli-compile
          - make -C client universal-compile
          - make -C client client-test
        services:
          - db
    - step:
        name: Server Test
        caches:
          - bundler-local
        script:
          - make -C server install-deps
          - make -C server setup-database-schema
          - make -C server test
          - make -C server load-live-data
        services:
          - db

definitions:
  caches:
    bundler-local: server/vendor
    node-client: client/node_modules
    node-schema: schema/json/node_modules
  services:
    db:
      image: postgres:10.0
      environment:
        POSTGRES_DB: 'esqulino_test'
        POSTGRES_USER: 'esqulino'
