image: marcusriemer/blockwerkzeug:test

# Builds usually take around 10 minutes
options:
  max-time: 20

clone:
  lfs: true

pipelines:
  default:
    - step:
        name: Client Build and Test
        artifacts:
          - client/dist/**
        script:
          - make -C client install-deps
          # Don't optimize for production, this takes very long
          # and produces multiple builds due to differential loading
          - NG_PROD='' make -C client client-compile-de
          - NG_PROD='' make -C client universal-de
          - make -C client cli-compile
          - make -C client client-test
    - step:
        name: Server Test
        caches:
          - bundler-local
        script:
          - make -C server install-deps
          - make -C server setup-database-schema
          - make -C server test
          - make -C server load-live-data
        services:
          - db

definitions:
  caches:
    bundler-local: server/vendor
    node-client: client/node_modules
    node-schema: schema/json/node_modules
  services:
    db:
      image: postgres:10.0
      environment:
        POSTGRES_DB: 'esqulino_test'
        POSTGRES_USER: 'esqulino'
