version: "3"

services:
  client:
    image: esqulino:development
    build:
      dockerfile: Dockerfile.development
      context: .
    environment:
      - TYPE=CLIENT
    volumes:
      - .:/srv/esqulino

  server:
    image: esqulino:development
    build:
      dockerfile: Dockerfile.development
      context: .
    environment:
      - TYPE=SERVER
      - BUNDLE_BIN=/usr/bin/bundler
      - RERUN_BIN=/srv/esqulino/server/vendor/bundle/ruby/2.4.0/bin/rerun
    ports:
      - 9292
    volumes:
      - .:/srv/esqulino
