version: "2"

services:
  client:
    image: marcusriemer/sqlino:client-dev
    build:
      dockerfile: Dockerfile.development.client
      context: .
    volumes:
      - .:/srv/esqulino
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TPUT_BIN=true

  server:
    image: marcusriemer/sqlino:server-dev
    build:
      dockerfile: Dockerfile.development.server
      context: .
    ports:
      - 9292:9292
    volumes:
      - .:/srv/esqulino
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TPUT_BIN=true
      - DATABASE_URL=postgresql://db/esqulino_dev
      
    depends_on:
      - db

  db:
    image: postgres:10.0
    environment:
      - POSTGRES_USER=esqulino_dev
      - POSTGRES_USER=esqulino

