version: "2"

services:
  test:
    image: marcusriemer/sqlino:test
    build:
      dockerfile: Dockerfile.test
      context: .
    volumes:
      - .:/srv/esqulino
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TPUT_BIN=true
      - DATABASE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:10.0
    environment:
      - POSTGRES_DB=esqulino_test
      - POSTGRES_USER=esqulino
