version: "2"

services:
  client:
    image: esqulino-client:development
    build:
      dockerfile: Dockerfile.development.client
      context: .
    volumes:
      - .:/srv/esqulino

  server:
    image: esqulino-server:development
    build:
      dockerfile: Dockerfile.development.server
      context: .
    ports:
      - 9292:9292
    volumes:
      - .:/srv/esqulino

