version: "3"

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=esqulino
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - data-postgres-volume:/var/lib/postgresql/data

  accounts:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
#      - DB_VENDOR=postgres
#      - DB_ADDR=db

volumes:
  data-files-volume:
  data-postgres-volume: