services:
  # The postgresql database
  db:
    image: postgres:15-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=esqulino
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - data-postgres-volume:/var/lib/postgresql/data

  # The rails server
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
    image: marcusriemer/blattwerkzeug:latest
    ports:
      - 9292:9292
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - RAILS_ENV=production
    volumes:
      - data-files-volume:/blattwerkzeug/rails_app/data
    tmpfs:
      - /blattwerkzeug/rails_app/server/tmp

volumes:
  data-files-volume:
  data-postgres-volume:
