version: "2"

services:
  client:
    image: marcusriemer/sqlino:client-dev
    build:
      dockerfile: Dockerfile.development.client
      context: .
    volumes:
      - .:/srv/esqulino

  server:
    image: marcusriemer/sqlino:server-dev
    build:
      dockerfile: Dockerfile.development.server
      context: .
    ports:
      - 9292:9292
    volumes:
      - .:/srv/esqulino

