version: "3"

services:
  base:
    image: marcusriemer/sqlino:base
    build:
      dockerfile: docker/Dockerfile.base
      context: .

  test:
    image: marcusriemer/sqlino:test
    build:
      dockerfile: docker/Dockerfile.test
      context: .
    volumes:
      - .:/srv/esqulino
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - TPUT_BIN=true
      - DATABASE_HOST=db
    entrypoint: ./docker/entrypoint-test.sh
    depends_on:
      - db
    tty: false
    stdin_open: false

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=esqulino_test
      - POSTGRES_USER=esqulino
