--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: id
  value_before_type_cast: 8ecf6bb1-02d1-4c04-8875-f1da62b7f720
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: name
  value_before_type_cast: Adventure
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: slug
  value_before_type_cast: cyoa
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: description
  value_before_type_cast: Write an adventure story and make your friends face-to-face
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: preview
  value_before_type_cast: 9a253ae0-8af1-4056-8984-50cb37b79c55
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: index_page_id
  value_before_type_cast: 352150eb-88bf-451b-821e-9fed8ce02cc2
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: active_database
  value_before_type_cast: default
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2018-02-20 20:48:21.695552'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2018-02-20 20:48:21.695552'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
