swagger: '2.0'

info:
  version: "0.1.0"
  title: esqulino

# Describe your paths here
paths:
  /api/project:
    get:
      description: |
        Retrieves all publicly available projects
      responses:
        200:
          description: Successful response
          schema:
            type: array
            title: ArrayOfProjects
            items:
              "$ref": "/ProjectDescription.json"
  /api/project/{id}:
    get:
      description: |
        Retrieves a specific project.
      parameters:
        - name: id
          in: path
          description: Id of the project to fetch
          required: true
          type: string
          format: uuid
      responses:
        200:
          description: |
            Succesful retrieval of a project.
          schema:
            "$ref": "/ProjectDescription.json"
