--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: id
  value_before_type_cast: 32056357-a38a-4258-9046-b8814cc35a55
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: name
  value_before_type_cast: Blog
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: slug
  value_before_type_cast: blog
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: description
  value_before_type_cast: Dein Blog, deine Regeln! Schreibe über Themen die dir am
    Herzen liegen und tausche dich in den Kommentaren mit deinen Lesern aus.
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: preview
  value_before_type_cast: a1986d62-0aec-4be4-a4db-cacd48f06453
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: index_page_id
  value_before_type_cast: 033f059a-ce96-405e-a415-de7575e05dae
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: active_database
  value_before_type_cast: default
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2018-02-20 20:48:21.690301'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2018-02-20 20:48:21.690301'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
