common: &common-settings
  client_dir: ../client/dist/browser
  schema_dir: ../schema/json
  query_dir: ../schema/graphql/queries

  mail:
    default_sender: "BlattWerkzeug <system@blattwerkzeug.de>"
    admin: "Marcus@GurXite.de"

  ide_service:
    exec:
      node_binary: <%= ENV['NODE_BIN'] || '/usr/bin/node' %>
      program: <%= ENV['CLI_PROGRAM'] || '../client/dist/cli/main.cli.js' %>
      mode: one_shot

  seed:
    data_dir: ../seed
    output: true

    # Common users that exist in the system
    users:
      guest: "00000000-0000-0000-0000-000000000001"
      system: "00000000-0000-0000-0000-000000000002"

    # IDs for the meta language
    meta:
      grammar:
        grammar: "89f9ca62-845c-435b-9b9a-cf52fe7df2b1"
        block_language: "b292612e-c58f-442f-9139-00b35a22f266"
      block_language:
        grammar: "df3ec59c-20c0-446d-8c84-7580e1c418bf"
        block_language: "81430cc2-bcff-4304-8cfd-6f05cf249a53"


  sentry:
    dsn: <%= ENV["SENTRY_DSN"] %>

  auth_tokens:
    access_token: 180 # 3 minutes
    refresh_token: 432000 # 5 days
    access_cookie: # Is empty because of the session duration
    refresh_cookie: 1209600 # 14 days

  auth_provider: ["Identity::Keycloak"]

  auth_provider_keys:
    keycloak_site: <%= ENV['KEYCLOAK_SITE'] || 'http://lvh.me:8080' %>
    keycloak_realm: <%= ENV['KEYCLOAK_REALM'] || 'BlattWerkzeug' %>

development:
  <<: *common-settings
  name: "Blattwerkzeug (Dev)"
  data_dir: <%= ENV['DATA_DIR'] || '../data/dev' %>


  project_domains: ["projects.localdomain:9292"]
  editor_domain: "lvh.me:9292"

  auth_provider: ["Identity::Developer", "Identity::Keycloak"]

test:
  <<: *common-settings
  name: "Blattwerkzeug (Test)"
  data_dir: "../data/test"
  project_domains: ["projects.localdomain:9292"]
  editor_domain: "localhost.localdomain:9292"

  # The IDE service will, under most circumstances, honor the
  # "mock: true" setting. This allows testcases to specify arbitrary
  # languages (and speeds up the whole ordeal).
  # But some tests verify that the actual code runs correctly,
  # so the common "exec" configuration must be available
  ide_service:
    mock: true
    exec:
      node_binary: <%= ENV['NODE_BIN'] || '/usr/bin/node' %>
      # Use the bundled version (with dependencies) on the testserver because
      # it has no `node_modules` folder available.
      program: <%= ENV['CLI_PROGRAM'] || '../client/dist/cli/bundle.cli.js' %>
      mode: one_shot


  seed:
    data_dir: ../seed-test
    output: <%= ENV['TEST_SEED_OUTPUT'] || false %>

    # Common users that exist in the system
    users:
      guest: "00000000-0000-0000-0000-000000000001"
      system: "00000000-0000-0000-0000-000000000002"

    # IDs for the meta language
    meta:
      grammar:
        grammar: "89f9ca62-845c-435b-9b9a-cf52fe7df2b1"
        block_language: "df3ec59c-20c0-446d-8c84-7580e1c418bf"
      block_language:
        grammar: "b292612e-c58f-442f-9139-00b35a22f266"
        block_language: "81430cc2-bcff-4304-8cfd-6f05cf249a53"


  auth_provider: ["Identity::Developer"]


production:
  <<: *common-settings
  name: "Blattwerkzeug"
  data_dir: <%= ENV['DATA_DIR'] || '../data/prod' %>
  project_domains: ["blattzeug.de"]
  editor_domain: "blattwerkzeug.de"
  auth_provider: ["Identity::Keycloak"]
