development:
  name: "Blattwerkzeug (Dev)"
  data_dir: <%= ENV['DATA_DIR'] || '../data/dev' %>
  client_dir: ../client/dist/browser
  schema_dir: ../schema/json
  project_domains: ["localhost.localdomain:9292"]
  editor_domain: "localhost:9292"
  mail:
    default_sender: "BlattWerkzeug <system@blattwerkzeug.de>"
    admin: "Marcus@GurXite.de"
  ide_service:
    exec:
      node_binary: /usr/bin/node
      program: ../client/dist/cli/main.cli.js
      mode: one-shot
  seed:
    data_dir: ../seed
    output: true
  sentry:
    dsn: <%= ENV["SENTRY_DSN"] %>
  auth_provider: [Google, Github, PasswordIdentity, Developer]
  auth_provider_keys:
    google_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    github_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    github_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  seed_users:
    guest: "00000000-0000-0000-0000-000000000001"
    system: "00000000-0000-0000-0000-000000000002"

test:
  name: "Blattwerkzeug (Test)"
  data_dir: "../data/test"
  client_dir: ../client/dist/browser
  schema_dir: ../schema/json
  project_domains: ["localhost.localdomain:9292"]
  editor_domain: "localhost.localdomain:9292"
  mail:
    default_sender: "BlattWerkzeug <system@blattwerkzeug.de>"
    admin: "Marcus@GurXite.de"
  # The IDE service will, under most circumstances, honor the
  # "mock: true" setting. This allows testcases to specify arbitrary
  # languages (and speeds up the whole ordeal).
  # But some tests verify that the actual code runs correctly,
  # so the "exec" configuration here may not be removed.
  ide_service:
    mock: true
    exec:
      node_binary: /usr/bin/node
      program: ../client/dist/cli/bundle.cli.js
      mode: one-shot
  seed:
    data_dir: ../seed-test
    output: false
  auth_provider: [Google, Github, PasswordIdentity, Developer]
  auth_provider_keys:
    google_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    github_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    github_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  seed_users:
    guest: "00000000-0000-0000-0000-000000000001"
    system: "00000000-0000-0000-0000-000000000002"

production:
  name: "Blattwerkzeug"
  data_dir: <%= ENV['DATA_DIR'] || '../data/dev' %>
  client_dir: ../client/dist/browser
  schema_dir: ../schema/json
  project_domains: ["blattzeug.de"]
  editor_domain: "blattwerkzeug.de"
  mail:
    default_sender: "BlattWerkzeug <system@blattwerkzeug.de>"
    admin: "Marcus@GurXite.de"
  ide_service:
    exec:
      node_binary: /usr/bin/node
      program: ../client/dist/cli/bundle.cli.js
      mode: one-shot
  seed:
    data_dir: ../seed
    output: true
  sentry:
    dsn: <%= ENV["SENTRY_DSN"] %>
  auth_provider: [Google, Github, PasswordIdentity]
  auth_provider_keys:
    google_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    github_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    github_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  seed_users:
    guest: "00000000-0000-0000-0000-000000000001"
    system: "00000000-0000-0000-0000-000000000002"