development:
  name: "Blattwerkzeug (Dev)"
  data_dir: ../data/test
  client_dir: ../client/dist
  schema_dir: ../schema/json

test:
  name: "Blattwerkzeug (Test)"
  data_dir: ../data/test
  client_dir: ../client/dist
  schema_dir: ../schema/json

production:
  name: "Blattwerkzeug"
  data_dir: ../data/dev
  client_dir: ../client/dist
  schema_dir: ../schema/json
  project_domains: [blattzeug.de]
