--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: id
  value_before_type_cast: '0583e928-3c8a-4f5a-9587-9fd69fe55534'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: default_database_id
  value_before_type_cast: bdd01223-0d02-42a0-ac88-fa34150258ae
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: name
  value_before_type_cast: Pokémon Vorstellung
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: slug
  value_before_type_cast: pokemon
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: description
  value_before_type_cast: Zeige deinen Freunden, welche Pokémon du gefangen hast!
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: preview
  value_before_type_cast: '08cf4332-c143-4d75-8439-0dd012090472'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: index_page_id
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2018-02-26 10:13:30.534056'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2019-01-16 08:40:08.436569'
- !ruby/object:ActiveModel::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
