--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: id
  value_before_type_cast: bbb246c3-a8c1-4aa1-bb3b-e3f0e3394969
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: default_database_id
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: name
  value_before_type_cast: Testprojekt für Web
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: slug
  value_before_type_cast: webtest
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: description
  value_before_type_cast: Gehen Sie weiter, hier gibt es nichts zu sehen ...
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: preview
  value_before_type_cast: '01396eae-a0cc-4147-84b4-60d455254cd1'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: index_page_id
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2018-02-25 19:13:02.563495'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2018-02-25 20:48:02.269305'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
