--- !ruby/object:Project
concise_attributes:
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: id
  value_before_type_cast: 867b74ad-9ab3-4402-98ee-cfb43d9de8b6
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: default_database_id
  value_before_type_cast: b2c9f3a4-9400-4442-bace-f9455b4db6d2
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: name
  value_before_type_cast: Olympia
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: slug
  value_before_type_cast: olympic
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: description
  value_before_type_cast: Statistiken zu olympischen Sommerspielen
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: public
  value_before_type_cast: true
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: preview
  value_before_type_cast: 60b1b3a3-63e5-41e3-b2a0-9943488081a7
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: index_page_id
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: created_at
  value_before_type_cast: '2018-02-26 10:35:11.345867'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: updated_at
  value_before_type_cast: '2018-05-15 18:43:22.85395'
- !ruby/object:ActiveRecord::Attribute::FromDatabase
  name: api_version
new_record: false
active_record_yaml_version: 2
